require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - lib/google-maps-directions.rb

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
